import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import { UserProvider } from './../UserContext';
import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-bdark`}
      >
        <EdgeStoreProvider>
        <UserProvider>
        {children}
        <Toaster/>
        </UserProvider>
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
